# -*- coding: utf-8 -*-
"""calculatrice.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X-l0n9UfD6BfN9-nwG2ZU260_BoFYxxI
"""

def addition(a, b):
    return a + b

resultat = addition(5, 3)
print(f"Le résultat est : {resultat}")